"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type CartLine={productId:string;slug:string;title:string;priceMmk:number;quantity:number;imageUrl:string|null;selectedLevel?:string|null};
export const cartLineKey=(item:Pick<CartLine,"productId"|"selectedLevel">)=>`${item.productId}::${item.selectedLevel??""}`;
type CartContextType={items:CartLine[];count:number;subtotal:number;add:(product:Omit<CartLine,"quantity">,qty?:number)=>void;quantity:(key:string,q:number)=>void;remove:(key:string)=>void;clear:()=>void};
const CartContext=createContext<CartContextType|null>(null);
export function StoreProvider({children}:{children:ReactNode}) {const [items,setItems]=useState<CartLine[]>([]);const [ready,setReady]=useState(false);useEffect(()=>{try{const saved=localStorage.getItem("pnk-cart-v1");if(saved){const parsed=JSON.parse(saved);if(Array.isArray(parsed))setItems(parsed)}}catch{localStorage.removeItem("pnk-cart-v1")}setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem("pnk-cart-v1",JSON.stringify(items))},[items,ready]);const add=useCallback((product:Omit<CartLine,"quantity">,qty=1)=>setItems(previous=>{const key=cartLineKey(product);const found=previous.find(i=>cartLineKey(i)===key);return found?previous.map(i=>cartLineKey(i)===key?{...i,quantity:Math.min(20,i.quantity+qty)}:i):[...previous,{...product,quantity:Math.min(20,qty)}]}),[]);const quantity=useCallback((key:string,q:number)=>setItems(p=>q<1?p.filter(i=>cartLineKey(i)!==key):p.map(i=>cartLineKey(i)===key?{...i,quantity:Math.min(20,q)}:i)),[]);const remove=useCallback((key:string)=>setItems(p=>p.filter(i=>cartLineKey(i)!==key)),[]);const clear=useCallback(()=>setItems([]),[]);const value=useMemo(()=>({items,count:items.reduce((s,i)=>s+i.quantity,0),subtotal:items.reduce((s,i)=>s+i.quantity*i.priceMmk,0),add,quantity,remove,clear}),[items,add,quantity,remove,clear]);return <CartContext.Provider value={value}>{children}</CartContext.Provider>}
export function useCart(){const value=useContext(CartContext);if(!value)throw new Error("useCart must be within StoreProvider");return value}
