import{describe,it,expect}from"vitest";import{checkoutSchema,phoneSchema,printOrderSchema}from"./validation";
const order={customerName:"Reader",phone:"+95 9 123 456 789",address:"Example Street",city:"Yangon",township:"Kamayut",paymentMethod:"COD",items:[{productId:"cm123456789abc",quantity:2}],idempotencyKey:"order-once"};
const print={customerName:"Reader",phone:"09 123 456 789",uploadToken:"signed-authorization-token-long",storageKey:"print-orders/1234567890abcdef/550e8400-e29b-41d4-a716-446655440000.pdf",originalFileName:"book.pdf",mimeType:"application/pdf",fileSizeBytes:1024,printMode:"BW",paperSize:"A4",duplex:false,pageRange:"1-4, 6",copies:1,finishing:"None",fulfillment:"PICKUP",customerConfirmedRights:true};
describe("customer order server validation",()=>{
 it("accepts Myanmar phone formats and rejects malformed contacts",()=>{expect(phoneSchema.safeParse("+95 9 123 456 789").success).toBe(true);expect(phoneSchema.safeParse("hello").success).toBe(false)});
 it("requires contact, address, an enabled payment choice, and bounded item quantities",()=>{expect(checkoutSchema.safeParse(order).success).toBe(true);expect(checkoutSchema.safeParse({...order,items:[{productId:"cm123456789abc",quantity:21}]}).success).toBe(false);expect(checkoutSchema.safeParse({...order,phone:"no"}).success).toBe(false)});
 it("requires printing rights confirmation and strictly shaped private PDF metadata",()=>{expect(printOrderSchema.safeParse(print).success).toBe(true);expect(printOrderSchema.safeParse({...print,customerConfirmedRights:false}).success).toBe(false);expect(printOrderSchema.safeParse({...print,storageKey:"public/uploads/file.pdf"}).success).toBe(false);expect(printOrderSchema.safeParse({...print,fileSizeBytes:0}).success).toBe(false)});
 it("requires a complete delivery location for print fulfillment",()=>{expect(printOrderSchema.safeParse({...print,fulfillment:"DELIVERY"}).success).toBe(false);expect(printOrderSchema.safeParse({...print,fulfillment:"DELIVERY",address:"123 Example Road",township:"Kamayut",city:"Yangon"}).success).toBe(true)});
});
